name: Rasa Chatbot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Image
        run: docker build -t rasa-backend -f "Back End/Dockerfile.rasa" "./Back End"

      - name: Build Action Server Image
        run: docker build -t rasa-action -f "Back End/Dockerfile.action" "./Back End"

      - name: Build Frontend Image
        run: docker build -t rasa-frontend -f "Front End/Dockerfile.frontend" "./Front End"

      # Run Tests (Backend)
      - name: Run Tests (Backend)
        run: |
          docker run --rm rasa-backend rasa test --stories tests/ || echo "Backend test failed"

      # Run Frontend (Hanya contoh, sesuaikan dengan framework yang digunakan)
      - name: Run Tests (Frontend)
        run: |
          docker run --rm rasa-frontend npm test || echo "Frontend test failed"
